### PR TITLE
README: updated to be a reference to Quattor web site

### LINKED ISSUE #57: Documentation: move all the Aquilon documentation in a single repository
Currently, Aquilon documentation is spread between this repository (`README.md` describing the installation) and the [web site](http://www.quattor.org/documentation/2013/10/25/aquilon-site.html) (describing Aquilon DB configuration). I think that we should have on the documentation on one side, either this repo or the web site repo. I see pro and cons for both solutions:
- Pro (this repo):
  - Having it colocated with the code increases the chance to have it up-to-date
- Cons (this repo):
  - This information is mainly maintained by the community, not Aquilon developers
  - The web site allows better rendering thanks to Jekyll (and its CSS)
  - There is a complex workflow to merge this repo contents with the repo used by the main developers (outside GH)

So I would probably support moving everything to the web site.

In addition, after everything has been moved into one repo, I suggest that we process it  as part of the Quattor release documentation that we put on ReadTheDocs.

### PR DESCRIPTION
**Pull request by jouvin**
- README contents from #36 moved to Quattor web site

Fixes #57.

### CODE REVIEW

**Comment by ned21** [comment]
@jouvin - for our internal review process we need the commit log to have a [Change-Id: line.](https://gerrit-documentation.storage.googleapis.com/Documentation/2.13.7/user-changeid.html)

Please can you install this [hook](https://gerrit.googlesource.com/gerrit/+/master/gerrit-server/src/main/resources/com/google/gerrit/server/tools/root/hooks/commit-msg) in .git/hooks/commit-msg before submitting future requests?

For this commit, please can you then amend the commit log with a Change-Id line? (You can just pick the original commit id) We can't do it because the commit-id will change and GH won't see it as the same commit.

**Comment by jouvin** [comment]
Sure, I'll do it.

**Comment by stdweird** [comment]
@jouvin can you have a look at this? @urbonegi is trying to complete this workflow

**Comment by jouvin** [comment]
Sorry for overlooking this... Done!

**Comment by urbonegi** [comment]
Is tested and merged to master @MS. Will be merged to upstream in mid next week.

**Comment by urbonegi** [comment]
merged

**Pull request closed without merging**
