### PR TITLE
Fix sed command

### PR DESCRIPTION
**Pull request by samary**
sed command line was missing ':'.

Change-Id: I7a97683cc229c714d3239faeedc01ad8dfa07923

### CODE REVIEW

**Comment by jouvin** [comment]
Is this PR still needed? From what I can see, in 1.12.58, the problem is still there. I had suggest either to merge this PR or to remove the script if it is no longer needed (I have no clue about what is its purpose).

**Comment by urbonegi** [comment]
From the looks it seems to be used only outside MS. @jrha do you still need this? If this is something used outside only - i do not see issue in merging it :)

**Comment by jrha** [comment]
We don't use it.

**Comment by jouvin** [comment]
In fact the site who reported it doesn't use Aquilon as far as I know and @samary left this site... So I think in principle we could close this issue. But as the script is in the sources, if the error reported is a real one, better to fix it. Or if this script is useless nowadays (no clue what it was supposed to do...), better to remove it...

**Comment by jrha** [comment]
Agreed

**Comment by jouvin** [comment]
@urbonegi I suggest merging this PR which does fix a real problem or removing the script if you think it is of no use.

**Comment by urbonegi** [comment]
This script should remove the 'ms' it seems. Could anyone outside MS test this to see if it does anything useful and that changes indeed 'fixing' something. I would not just merge this - we need to test this and investigate if it indeed does anything useful. I suggest community should test this before we will merge. By testing I mean try running it - see if the 'sed' is really 'fixed' and then try to run unitests to see if they will not break. Or just close this one :)

**Comment by jouvin** [comment]
@urbonegi we should not just close this issue as the script really has a bug (with `sed` you need a pattern delimiter before the pattern, after the pattern and **after the replacement**). But I agree with you that merging the proposed fix is probably not the valid approach. Based on my experience, this script is completely useless and comes from earlier time in Aquilon, before we started to have a cleaner installation process (in particular with the `aqd.conf.noms`. My proposal then is to close this PR **and** open a new one removing this script. I can do it if you want.

**Comment by jrha** [comment]
@jouvin that sounds like the correct approach to me

**Comment by jouvin** [comment]
As agreed in the discussion, remove this script #100 rather than fix it...

**Pull request closed without merging**
