### PR TITLE
README: add instructions to add Change-Id line using the gerrit commit-msg hook

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by urbonegi** [comment]
I suggest to better move that section into the documentation page (http://www.quattor.org/aquilon/00-install.html) together with the rest of docs if we already moved that put away frrom the README. It could be in the separate page called 'Contribute' or 'Development' so that all the instructions would be in the same place..

**Comment by stdweird** [comment]
@urbonegi ok, i'll do so. but is this PR otherwsie in the correct format? or is anything else also required

**Comment by urbonegi** [comment]
Looks good. Just maybe you could add an example commit message format in general.
Example Commit message: 
Short Summary of the change

Details what was done
Details what more was done

Change-Id: I9f8d7d0f656e72877c436727d0e4a8d8a62a4b89

**Comment by stdweird** [comment]
@urbonegi and do you really want PRs with single (squashed) commit? see eg https://github.com/quattor/aquilon/pull/58. first commit is a sort without any changes, but if we squash those 3 commits it's very hard to tell not that much actually changed.

**Comment by urbonegi** [comment]
it is not necessarily one PR one commit. The idea - a commit should beworth staying in the master history: history should not contain half way there commits. If history is clean and structured, then reverting (if needed) is easy and cannot cause a mess. In the example #58 , the change message could contain details of what was done (sorted dependencies, added python-psycopg2 dependency etc.).
Having 3 commits with change ids would also mean that these would go through CI/CD separately and that does not makes sense in this case..

**Pull request closed without merging**
