### PR TITLE
Revert "Fix Aquilon README"

### PR DESCRIPTION
**Pull request by ned21**
Reverts quattor/aquilon#36

DO NOT MERGE. This mostly exists to allow us to track the PR that needs to go into the real upstream branch.

### CODE REVIEW

**Comment by jouvin** [comment]
See also the proposal in #57 that may impact this particular issue.

**Comment by jrha** [comment]
@ned21 I can forcibly revert the upstream branch and re-open the original PR, which might be cleaner...

**Comment by jouvin** [comment]
@jrha I think that @ned21 said it was just a reminder for MS and was not intended to be merged... I'd prefer that we close this issue after agreeing that the README contents should be moved to the web site as proposed in #57... I'm just waiting the green light to do it.

**Comment by ned21** [comment]
Let's discuss on Thursday. Forcibly reverting the upstream branch from our internal copy and re-opening the original PR might be the right way to go but let's discuss with Dave.

**Comment by jouvin** [comment]
@ned21 I'll try to join tomorrow but I cannot promise. I don't really see why you would need to forcibly reverting the change. Is not pulling/merging this change to your internal copy enough? Git should make this pretty easy, shouldn't it?

And again, an alternative would be to move the contents of this README to the web site as proposed in #57... I have not seen any feedback about it.

**Comment by jrha** [comment]
It's not a question of what the technology can achieve, it's a question of what workflow we want to implement... discussing on Thursday is a good idea.

**Comment by jouvin** [comment]
Sure the workflow discussion is important... but this particular case is probably not the most appropriate if we agree that the Aquilon documentation should not be in the same repo for the reason explained in #57. In this case, the README should be much shorter with a reference to the documentation wherever it is hosted (web site or ReadTheDocs).

**Comment by ned21** [comment]
@jouvin Unfortunately Dave cannot make this Thursday but should be able to make next week. We need the upstream branch to match our internal copy which has moved on since this was merged so to avoid merge conflicts it would be better to revert this and then we'll use it to practice how the process should work where we pull in the branch locally, put it through our internal pipeline and push it back out.

I agree #57 might/should change this. but now it's been merged we need to straighten out the upstream branch again so we can resume pushing out code.

@jrha - are you OK to force-push the branch and then re-open the PR? Dave and team will then test pulling down the PR and push it back out and confirm that process works for us for accepting patches.

**Comment by jouvin** [comment]
I am not sure myself to make it tomorrow, so let's try to converge via this discussion... We are not far. It's fine with me to forcibly revert as long as the new contents make it somewhere, my previous messages could have been ambiguous. If there is an agreement about #57, I'd suggest no to reopen the PR after being reverted but rather put this contents on the Aquilon installation page on the web site (as part of https://github.com/quattor/quattor.github.com/pull/211?) and open a new PR in this repo to clean up the README file once we have agreed on the workflow. If it is agreed, I can take care of it.

**Comment by jrha** [comment]
@jouvin The stand-up is on Thursday, which is not tomorrow.
@ned21 I will revert the upstream branch this afternoon, unfortunately I cannot make the stand-up next week due to a meeting in Brighton.

**Comment by jouvin** [comment]
@jrha thanks for the remark, travelling too much, I am a bit lost... I should be able to make it this week then... I'll ensure that I have an up-to-date copy of the merged PR and I'll add it to https://github.com/quattor/quattor.github.com/pull/211.

**Comment by jrha** [comment]
Original PR reverted, I've opened a copy in #61, this one can be closed now.

**Pull request closed without merging**
