### PR TITLE
JSON Formatter

### PR DESCRIPTION
**Pull request by jrha**
Implement a JSON formatter for the `aqd` RESTish interface.

This is required to support the "awesome sauce" that we have been brewing.

### CODE REVIEW

**Comment by jrha** [comment]
DO NOT MERGE

This PR is for reference only (it should go back into the codebase via MS).

**Comment by gombasg** [comment]
Adding a 3rd formatter which returns similar but not necessarily the same data as the other two (raw, protobuf) is not maintainable. The strategic long-term solution is to renovate the protobuf formatter based on version 3 of the protobuf specification, which does include a canonical translation from protobuf to JSON. Ideally, the broker would only produce protobuf 3 data; all translation to human-readable format would happen on the client side.

**Comment by ned21** [comment]
Superseded by #71

**Comment by jrha** [comment]
Closing - will focus on supporting protobuf v3 instead

**Pull request closed without merging**
